### ISSUE TITLE
Los campos no deben permitir el ingreso de valores incorrectos

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo#11]
![imagen](https://github.com/UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo/assets/8345007/affd8dc2-d563-4531-b3dd-26c317564ade)

El tiempo no puede ser negativo

**Comment by edme88** [comment]
Empleando Firefox, permite ingresar valores negativos. 
![imagen](https://github.com/UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo/assets/8345007/75af785f-f0bf-4d6d-8b26-964266c2476a)

Si no pueden solucionar el problema, entonces por lo menos deberían hacer que no realice el cálculo y mostrar un mensaje de alerta al usuario.

![Uploading imagen.png…]()

**Comment by LorenzoGalaverna** [comment]
Que navegador utiliza? A nosotros no nos permite ingresar signos -

**Comment by LorenzoGalaverna** [comment]
creemos que ahora no se puede

**Comment by edme88** [comment]
![imagen](https://github.com/UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo/assets/8345007/e1ab6b01-267a-4b4f-9d50-280b9f0ecb86)
Si bien no pude escribir "-19" manualmente, escribí cero y presione en mi teclado la flecha para abajo.

En todo caso, si no pueden hacer que el usuario NO ingrese números negativos en el tiempo, por lo menos hagan que muestre un mensaje de error indicando que el tiempo no puede ser negativo y blanqueen el campo.
