### ISSUE TITLE
Ingresando algunos valores, la página no ejecuta la animación

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo#30]
![imagen](https://github.com/UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo/assets/8345007/662d97f2-29e8-4016-9f5f-f3422f0b1a7b)

**Comment by LorenzoGalaverna** [comment]
Ahora no se pueden ingresar definitivamente los vlaores negativos, por lo que este error quedaria solucionado

**Comment by edme88** [comment]
![imagen](https://github.com/UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo/assets/8345007/3df0e0f4-7d13-4fcf-894b-6b825ce7b125)

**Comment by LorenzoGalaverna** [comment]
Hemos hecho que al superar un determinado valor, entonces el grafico no sera realizado, pero el calculo si.
En esos casos sale una alerta que notifica al usuario.
