### ISSUE TITLE
No emplear variables globales

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo#32]
https://github.com/UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo/blob/fb4a1da2abec774fdc3176c9da01e4e9175ebdd0/script.js#L37-L50

Solo se permite emplear como variable global aquella que sea necesario SI o SI para animación. Pero gran parte de las variables que están empleando pueden ser encapsuladas en la función que las requiera.

**Comment by LorenzoGalaverna** [comment]
anchoAuto quedo en forma de variable global ya que es utilizada en multiples funciones.
Esta junto con las demas variables globales, son las que permiten la animacion.
