### ISSUE TITLE
Falta Documentación en algunas funciones

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo#36]
https://github.com/UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo/blob/fb4a1da2abec774fdc3176c9da01e4e9175ebdd0/script.js#L22

https://github.com/UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo/blob/fb4a1da2abec774fdc3176c9da01e4e9175ebdd0/script.js#L59

**Comment by LorenzoGalaverna** [comment]
La documentacion de la funcion aniimar, esta encima de ella.

**Comment by edme88** [comment]
Aún existen funciones sin documentación
https://github.com/UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo/blob/0070328b466b618449fb638b43e6fa35aa707c75/script.js#L22

https://github.com/UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo/blob/0070328b466b618449fb638b43e6fa35aa707c75/script.js#L361

https://github.com/UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo/blob/0070328b466b618449fb638b43e6fa35aa707c75/script.js#L381
