### ISSUE TITLE
Emplear el atributo maxlength para que el usurario no pueda ingresar valores "muy grandes"

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo#6]
![imagen](https://github.com/UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo/assets/8345007/56bf6fba-178e-4cea-8f1a-afed4936e655)

Sería conveniente que limiten la cantidad de números que se pueden ingresar a 8 máximo por ejemplo.

**Comment by LorenzoGalaverna** [comment]
La clase maxlength era ignorada por el navegador, en reemplazo, creamos un trigger extra en el archivo javascript
