### ISSUE TITLE
Sugerencia: Una vez que el automovil llego a la distancia máxima, la animación debe detenerse

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2024-CarranzaSantiago-GalavernaLorenzo#9]

**Comment by LorenzoGalaverna** [comment]
Creemos que no es necesario, ya que se repite automaticamente, y cuando alguien carga otro dato, este se actualiza instantaneamente

**Comment by santiago6124** [comment]
Finalmente, decidimos tener en cuenta esta sugerencia. Muchas gracias!
